services:
  kratos-db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: ${KRATOS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KRATOS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${KRATOS_POSTGRES_DB}
    volumes:
      - kratos_db_data:/var/lib/postgresql/data
    networks:
      - fumode-net
    ports:
      - "5432:5432"

  kratos-migrate:
    image: kratos
    build: ./kratos
    restart: on-failure
    depends_on:
      - kratos-db
    environment:
      - DSN=${KRATOS_DB_DSN}
    command: migrate sql -e --yes
    networks:
      - fumode-net

  kratos:
    image: kratos
    build: ./kratos
    depends_on:
      - kratos-migrate
    restart: unless-stopped
    environment:
      - DSN=${KRATOS_DB_DSN}
#      - COURIER_SMTP_CONNECTION_URI=${KRATOS_SMTP}
    networks:
      - fumode-net
    ports:
      - "4433:4433"
      - "4434:4434"

volumes:
  kratos_db_data:

networks:
  fumode-net:
