openapi: 3.0.3
info:
  title: Fumode REST API
  description: API specification for Fumode app
  version: 1.0.0
servers:
  - url: 'http://localhost:4000/v1'
tags:
  - name: User
    description: Operations accessible to regular users.
  - name: Admin
    description: Operations restricted to administrative users.
paths:
  /furniture:
    $ref: "./paths/furniture.yaml"
  /furniture/{id}:
   $ref: "./paths/furniture_item.yaml"
  /users/{id}/cart:
    $ref: "./paths/cart.yaml"
  /orders:
    $ref: "./paths/orders.yaml"
