openapi: 3.0.1
info:
  title: Fumode REST API
  description: The REST API for Fumode
  version: 1.0.0
servers:
  - url: 'http://localhost:4000/v1'
paths:
  /furniture:
    $ref: "./paths/furniture.yaml/#/GetAllFurniture"

