openapi: 3.1.0
info:
  title: Fumode REST API
  description: The REST API for Fumode
  version: 1.0.0
servers:
  - url: 'http://localhost:4000/v1'
paths:
  /furniture:
    get:
      tags:
        - Furniture
        - Admin
        - User
      description: Retrieve a list of all furniture that matches the filter
      summary: List all furniture
      parameters:
        - in: query
          name: name
          schema:
            type: string
            description: The filter for furniture name
            example: cushion
          required: false
        - in: query
          name: page
          schema:
            type: int
            description: The page number
            example: 1
            minimum: 1
          required: false
        - in: query
          name: page_size
          schema:
            type: int
            description: The page_size
            example: 10
            minimum: 10
          required: false
        - in: query
          name: category
          schema:
            type: string
            description: The filter for category
          required: false
        - in: header
          description: The User session cookie retrieved after completing self-service (required for browser only)
          name: Cookie
          schema:
            type: string
            description: The session cookie
            example:  ory_kratos_session=<cookie>
        - in: header
          name: Authorization
          description: The User session token retrieved after completing self-service flow (required for non-browser only)
          schema:
            type: string
            format: bearer
            description: The session token
            example: Bearer <token>
      responses:
        200:
          description: Successfully retrieved a list of furniture
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: "./schemas/pagination.yaml/#/PaginationMetadata"
                  items:
                    type: array
                    description: A list of furniture
                    items:
                      $ref: "./schemas/furniture_listing.yaml/#/FurnitureListing"
