openapi: 3.1.0
info:
  title: Fumode REST API
  description: The REST API for Fumode
  version: 1.0.0
servers:
  - url: 'http://localhost:4000/v1'
paths:
  /furniture:
    get:
      tags:
        - Furniture
        - Admin
        - User
      description: Retrieve a list of all furniture that matches the filter
      summary: List all furniture
      parameters:
        - in: query
          name: name
          schema:
            type: string
            description: The filter for furniture name
            example: cushion
          required: false
        - in: query
          name: page
          schema:
            type: int
            description: The page number
            example: 1
            minimum: 1
          required: false
        - in: query
          name: page_size
          schema:
            type: int
            description: The page_size
            example: 10
            minimum: 10
          required: false
        - in: query
          name: category
          schema:
            type: string
            description: The filter for category
          required: false
        - in: header
          description: The User session cookie retrieved after completing self-service (required for browser only)
          name: Cookie
          schema:
            type: string
            description: The session cookie
            example:  ory_kratos_session=<cookie>
        - in: header
          name: Authorization
          description: The User session token retrieved after completing self-service flow (required for non-browser only)
          schema:
            type: string
            format: bearer
            description: The session token
            example: Bearer <token>
      responses:
        200:
          description: Successfully retrieved a list of furniture
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: "#/components/schemas/PaginationMetadata"
                  items:
                    type: array
                    description: A list of furniture
                    items:
                      $ref: "#/components/schemas/Furniture"

components:
  schemas:
    PaginationMetadata:
      type: object
      properties:
        current_page:
          type: integer
          minimum: 1
          description: The current page number.
          example: 1
        total_pages:
          type: integer
          description: The total number of pages.
          example: 10
          minimum: 1
        page_size:
          type: integer
          description: The number of items per page.
          example: 20
          minimum: 1
        total_items:
          type: integer
          description: The total number of items across all pages.
          example: 195
          minimum: 0
      required:
        - current_page
        - total_items
        - page_size
        - total_items
    Furniture:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
          description: The ID of the furniture
          example: 1
        name:
          type: string
          description: The name of the furniture
          example: Modern Sofa
        description:
          type: string
          description: The description of the furniture
          example: Elegant 3-seater
        price:
          type: number
          format: float
          description: The price of the furniture
          example: 123.99
        stock:
          type: integer
          description: The number of stock available
          min: 1
          example: 12
        main_image_url:
          type: string
          format: uri
          description: The url for the main image of the furniture
          example: https://example.com/images/chair_main.jpg
        additional_image_urls:
          type: array
          description: Additional image urls for the furniture
          items:
            type: string
          examples:
            - https://example.com/images/chair_side.jpg
            - https://example.com/images/chair_back.jpg
            - https://example.com/images/chair_detail.jpg
        category:
          type: object
          properties:
            id:
              type: integer
              min: 1
              description: The category id
              example: 1
            name:
              type: string
              description: The name of the category
              example: Sofas
    FurnitureListing:
      type: object
      properties:
        id:
          type: integer
          min: 1
          description: The ID of the furniture
          example: 1
        name:
          type: string
          description: The name of the furniture
          example: Dining Table
        price:
          type: number
          description: The price of the furniture
          format: float
          example: 153.45
        main_image_url:
          type: string
          format: uri
          description: The main image of the furniture
          example: https://example.com/images/chair_main.jpg
